export { default as GlobalAssistant } from './GlobalAssistant'
export { default as ChatPanel } from './ChatPanel'
export { default as Orb } from './Orb'
export { default as DemoVideoPlayer } from './DemoVideoPlayer'
export { clipFromAnswer } from './clip'
export type { DemoClipStep } from './clip'
export type { DemoVideoPlayerProps } from './DemoVideoPlayer'
export { default as AIWatch, AIWatchCard } from './AIWatch'
export { WATCH_ADVISORIES } from './watchData'
export { default as SelfUpdate } from './SelfUpdate'
export { default as ScriptedDemo } from './ScriptedDemo'
export { default as RoleProvider } from './RoleContext'
export { useRole } from './roleStore'
export { openAssistant, openAssistantWatch } from './types'
export type { Role, Lang, KBEntry } from './knowledgeBase'
export type { ChatMessage } from './types'
export type { WatchAdvisory, WatchStatus } from './watchData'
export type { OrbProps, OrbState } from './Orb'
